apiVersion: v1
kind: Service
metadata:
  name: cavalos-service
spec:
  # IP externo, acessível fora do Cluster
  type: NodePort
  selector:
    # Todo Pod com essa tag fará parte deste serviço
    app: cavalos
  ports:
  - name: cavalos
    protocol: TCP
    # Porta na qual o nó recebe requisições
    port: 4000
    # Porta para a qual o nó redireciona a requisição
    targetPort: 4000