apiVersion: apps/v1
kind: Deployment
metadata:
# Nome do Deployment
  name: cavalos-deploy
spec:
  # Número de cópias
  replicas: 1
  # Especificar o rótulo
  selector:
    matchLabels:
      # Deployment vai selecionar todo Pod com esse rótulo
      app: cavalos
  # Modelo que vai ser usado para construir os Pods
  template:
    metadata:
      labels:
        # Pods terão esse rótulo, sendo selecionados por esse deployment
        app: cavalos
      
    spec:
      containers:
      - name: cavalos
        image: iz120/cavalos
        imagePullPolicy: Never
        resources:
          limits:
            memory: 256Mi
            cpu: 1