apiVersion: v1
kind: Service
metadata:
  name: haras-front-service
spec:
  # IP externo, acessível fora do Cluster
  type: LoadBalancer
  selector:
    # Todo Pod com essa tag fará parte deste serviço
    app: haras-front
  ports:
  - name: haras-front
    protocol: TCP
    # Porta na qual o nó recebe requisições
    port: 3000
    # Porta para a qual o nó redireciona a requisição
    targetPort: 3000