apiVersion: apps/v1
kind: Deployment
metadata:
# Nome do Deployment
  name: proprietarios-deploy
spec:
  # Número de cópias
  replicas: 1
  # Especificar o rótulo
  selector:
    matchLabels:
      # Deployment vai selecionar todo Pod com esse rótulo
      app: proprietarios
  # Modelo que vai ser usado para construir os Pods
  template:
    metadata:
      labels:
        # Pods terão esse rótulo, sendo selecionados por esse deployment
        app: proprietarios
      
    spec:
      containers:
      - name: proprietarios
        image: iz120/proprietarios
        imagePullPolicy: Never
        resources:
          limits:
            memory: 256Mi
            cpu: 1

---
apiVersion: v1
kind: Service
metadata:
  # Nome diferente do serviço tipo NodePort
  name: proprietarios-clusterip-service
spec:
  selector:
    app: proprietarios
  ports:
  - name: proprietarios
  protocol: TCP
  port: 5000
  taregtPort: 5000